name: Build APK

on:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH


    - name: Setup Android environment
      uses: android-actions/setup-android@v3
  

    - name: Build dependencies
      run: |
        mkdir ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        git clone --depth=1 -b main https://github.com/maskedeken/AndroidLibXrayLite.git
        cd AndroidLibXrayLite
        gomobile init
        go mod tidy -v
        gomobile bind -v -androidapi 21 -trimpath -ldflags='-s -w -buildid=' -tags with_gvisor ./
        mkdir -p ${{ github.workspace }}/V2rayNG/app/libs
        cp *.aar ${{ github.workspace }}/V2rayNG/app/libs/

    - name: Build APK
      run: |
        cd ${{ github.workspace }}/V2rayNG
        chmod 777 *
        export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/release/
